# Generated by Django 3.0.3 on 2020-02-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destin',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
